services:
  - type: web
    name: airline-booking-agent
    env: python
    buildCommand: python -m pip install -r requirements.txt && python -c "import urllib.request; urllib.request.urlretrieve('https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat', 'data/airports.dat')"
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: MY_TEST_PHONE
        sync: false
      - key: MY_TEST_EMAIL
        sync: false
      - key: UPSTREAM_API_URL
        value: https://zz1mpoguje.execute-api.us-east-1.amazonaws.com/default/airline-assessment
